Fix build with gcc version less then 10
rhboot/efivar pull request #181
Opened 2021-10-28 21:41 UTC by 0x501D

We cannot use VERSION macro in current way because __asm__
cannot be placed in function definition. Also this patch fixes
build with clang.

2021-11-11 21:37 UTC, frozencemetery requested changes
- Please rebase on main - this code has moved
- I'm unable to reproduce build failure with clang (main builds fine) - please either clarify or remove
- I would prefer you add another conditional definition for VERSION rather than introducing a new macro - this should just be a third case to consider and shouldn't involve touching the existing usages.

2021-11-11 21:51 UTC, frozencemetery commented
Note also that it's generally easier for maintainers to work with your PRs if you use feature branches (i.e., something other than main in your fork).  It's not technically wrong to do it the way you have, but I'm less likely to do minor fixups myself and more likely to ask you to do them.

2021-11-12 06:01 UTC, 0x501D commented
Thanks for the answer, I will rebase and rework if it still actual.

2021-11-17 21:17 UTC, frozencemetery commented
This is getting pulled into #187

2021-11-17 21:17 UTC, closed without merging